version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Install phase"
      - node -v && npm -v
  pre_build:
    commands:
      - echo "Pre-build"
      - cd frontend              # 이미지 확인 결과, 여기에 package.json이 있습니다.
      - npm ci                   # npm install보다 빌드 환경에 최적화된 명령어입니다.
  build:
    commands:
      - echo "Build"
      - npm run build            # Vite 빌드 실행 (dist 폴더 생성)
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - 'appspec.yml'             # 루트에 있는 appspec 파일 포함
    - 'scripts/**/*'            # 스크립트 폴더 포함 (있을 경우)
    - '**/*'                    # 그 외 빌드된 모든 파일 포함
  base-directory: frontend/dist # Vite의 빌드 결과물 경로
